pipeline:
  name: CI-demo
  identifier: CIdemo
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: demogithubconnector
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Create_build
                  identifier: Create_build
                  spec:
                    connectorRef: account.harnessImage
                    image: node:20
                    shell: Sh
                    command: |-
                      mkdir /harness/apps
                      cd /harness/apps
                      npx @angular/cli new my-angular-app
                      cd my-angular-app && npm install
                      npx ng build --configuration production
                      cd ../.. && npm install && npm run zip
                      ls -la
                  when:
                    stageStatus: Success
                    condition: "true"
