pipeline:
  name: CI-demo-1
  identifier: CIdemo1
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: demogithubconnector
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Create_Build
                  identifier: Create_Build
                  spec:
                    connectorRef: account.harnessImage
                    image: node:20
                    shell: Sh
                    command: |-
                      mkdir /harness/apps
                      cd /harness/apps
                      npx @angular/cli new my-angular-app
                      cd my-angular-app && npm install
                      npx ng build --configuration production
                      cd ../.. && npm install && npm run zip
                      ls -la
                      mv build.zip build_${HARNESS_JOB_ID}.zip
                      ls -la
                      export artifact="build_*.zip"
                    envVariables:
                      HARNESS_JOB_ID: <+pipeline.sequenceId>
                    outputVariables:
                      - name: artifact
                        type: String
                        value: artifact
                  when:
                    stageStatus: Success
                    condition: "true"
              - step:
                  type: Sonarqube
                  name: Sonarqube_1
                  identifier: Sonarqube_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      workspace: /harness
                      detection: auto
                    advanced:
                      log:
                        level: debug
                    auth:
                      access_token: <+secrets.getValue("account.Sonar-key")>
                      domain: https://sonar.arlocloud.com
                      ssl: true
                    tool:
                      project_key: CI-demo
                  when:
                    stageStatus: Success
                    condition: "true"
              - step:
                  type: Run
                  name: Protecode
                  identifier: Protecode
                  spec:
                    connectorRef: account.harnessImage
                    image: node:20
                    shell: Sh
                    command: |-
                      #!/bin/bash

                      # Simulate Jenkins parameter
                      runProtecode=true  # Set to true or false depending on whether to run

                      if [ "$runProtecode" = true ]; then
                        cd "/harness" || exit 1
                        pwd && ls
                        echo "Uploading"
                        curl -H "Authorization: Bearer <+secrets.getValue("account.Protecode_password")>" \
                               -H "Group: 1229" \
                               -T hmswebclient_*.zip \
                               "https://protecode-sc.com/api/upload/"
                      else
                        echo "Protecode step skipped due to 'when' condition"
                      fi
                    envVariables:
                      BRANCH_NAME: <+codebase.targetBranch>
                  when:
                    stageStatus: Success
                    condition: "true"
              - step:
                  type: ArtifactoryUpload
                  name: Upload_to_artifactory
                  identifier: Upload_to_artifactory
                  spec:
                    connectorRef: Artifactory_connector
                    target: angular-npm/
                    sourcePath: <+pipeline.stages.Build.spec.execution.steps.Create_Build.output.outputVariables.artifact>
                  when:
                    stageStatus: Success
                    condition: "true"
